### ISSUE TITLE
leaving blank the extension field acts differently for open_file (grabs all) and resample_file (grabs none).

### ISSUE THREAD

**Issue by jeanphilippegoldman** [jeanphilippegoldman/plugin_filetools#10]
rolando says > You're right. What should we do here? 1) when leaving blank the extension in resample_file, open all audio files? 2) Use a * to open all files and do not open anything when the field is empty?

they should act alike. i commited so that "" and "*" in open_file are the same.

maybe you could use line 40-60 in open_file in resample_file

**Comment by rolandomunoz** [comment]
Oh... I have seen a problem in line 41 of `template_open_files3.praat` in Ubuntu. We expect that `""` behaves alike `"*"` (open all valid files in the Object window).  In order to do that, you added `or file_extension$ == "*"`

```
if file_extension$ == "" or file_extension$ == "*"
```

However this only works for Windows. Later, in the code:

```
  file_list = Create Strings as file list: "fileList", folder$ + "/*" + file_extension$
```

So, if `file_extension$ ="*"`, you've got:
```
  file_list = Create Strings as file list: "fileList", folder$ + "/**"
```
which opens nothing in Ubuntu, and maybe MAC.

Maybe, we could do the following:

```
file_extension$ = if file_extension$ == "*" then "" else file_extension$ fi
if file_extension$ == ""
  ...
```
This could work for Windows and Ubuntu.
Should I fix it?

**Comment by rolandomunoz** [comment]
I fixed it. The solution was to add the following line:

```
files$ = if sound_file_extension$ == "" or sound_file_extension$ == "*" then "*" else "*." + sound_file_extension$ fi 
```

I put it in:
- template_resample_files
- template_open_files3
- template_get_durations

Could you test it on Windows, please?

By the way, I'm not sure about this new behavior. I mean, this is ok for  `Open fies...` because you want to open all files when use `*`. However, there is no point to using it in `Get durations` or `Resample files...` commands since they are supposed to work only with audio files. Maybe, we could restrict the range of `*` to a list of valid audio extensions? 

Also, do we want allow expressions like `*.wav`, `*.TextGrid` in the extension field?

**Comment by jeanphilippegoldman** [comment]
looks ok to me after test.
closing.
please reopen if needed.
